#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================================
# Smart Proxy Server - singtest
#
# Test one generated sing-box outbound candidate for basic connectivity.
#
# Usage:
#   bash singtest.sh <candidate.json>
#
# The input JSON is the outbound fragment generated by maker.sh.
# The maker metadata "tag" is removed from the fragment and recreated as the
# real sing-box outbound tag inside a temporary full configuration.
#
# The test intentionally does NOT perform speed benchmarking, jitter scoring,
# or ranking. It only answers:
#
#   "Can this candidate establish usable application traffic through sing-box?"
#
# The actual connectivity probe is performed through a temporary local SOCKS5
# listener using curl. No ICMP/ping is used.
# ============================================================================

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SING_BOX="${SING_BOX_BIN:-sing-box}"
TARGET_URL="${SINGTEST_URL:-https://google.com/}"
TIMEOUT="${SINGTEST_TIMEOUT:-8}"
PORT="${SINGTEST_PORT:-19180}"
WORK_DIR="${SINGTEST_WORK_DIR:-/tmp/smartproxy-singtest}"

fatal(){ printf '[✗] %s\n' "$*" >&2; exit 1; }
info(){ printf '[*] %s\n' "$*"; }
success(){ printf '[✓] %s\n' "$*"; }
warning(){ printf '[!] %s\n' "$*" >&2; }

usage(){
    printf 'Usage: %s <candidate.json>\n' "$(basename "$0")" >&2
    exit 2
}

require_cmd(){
    command -v "$1" >/dev/null 2>&1 || fatal "Missing required command: $1"
}

is_number(){
    [[ "${1:-}" =~ ^[0-9]+([.][0-9]+)?$ ]]
}

[[ $# -eq 1 ]] || usage
CANDIDATE="$1"
[[ -f "$CANDIDATE" ]] || fatal "Candidate not found: $CANDIDATE"

require_cmd "$SING_BOX"
require_cmd python3
require_cmd curl
require_cmd timeout
require_cmd flock

mkdir -p "$WORK_DIR"
RUN_DIR="$WORK_DIR/run-$$"
mkdir -p "$RUN_DIR"

CONFIG_FILE="$RUN_DIR/config.json"
PROBE_LOG="$RUN_DIR/sing-box.log"
PROBE_ERR="$RUN_DIR/sing-box.err"
HTTP_CODE_FILE="$RUN_DIR/httpcode"
CURL_ERR="$RUN_DIR/curl.err"
RESULT_FILE="$RUN_DIR/result"
PID=""

cleanup(){
    if [[ -n "${PID:-}" ]] && kill -0 "$PID" 2>/dev/null; then
        kill "$PID" 2>/dev/null || true
        wait "$PID" 2>/dev/null || true
    fi
}
trap cleanup EXIT INT TERM

###############################################################################
# Candidate metadata
###############################################################################
read_metadata(){
    python3 - "$CANDIDATE" <<'PY'
import json
import sys

with open(sys.argv[1], encoding='utf-8') as fh:
    candidate = json.load(fh)

transport = (candidate.get('transport') or {}).get('type', 'tcp')
tls = candidate.get('tls') or {}
security = 'tls' if tls.get('enabled') else 'none'
proto = candidate.get('type', 'unknown')
server = candidate.get('server', '')
port = candidate.get('server_port', '')
name = candidate.get('tag', 'candidate')

print(f'name={name}')
print(f'protocol={proto}')
print(f'server={server}')
print(f'port={port}')
print(f'transport={transport}')
print(f'security={security}')
PY
}

META="$(read_metadata)" || fatal "Invalid candidate JSON"

get_meta(){
    local key="$1"
    awk -F= -v k="$key" '$1==k {sub(/^[^=]*=/,""); print; exit}' <<< "$META"
}

NAME="$(get_meta name)"
PROTOCOL="$(get_meta protocol)"
SERVER="$(get_meta server)"
SERVER_PORT="$(get_meta port)"
TRANSPORT="$(get_meta transport)"
SECURITY="$(get_meta security)"

###############################################################################
# Build temporary full sing-box configuration
###############################################################################
python3 - "$CANDIDATE" "$CONFIG_FILE" "$PORT" <<'PY'
import json
import sys

candidate_path, config_path, port = sys.argv[1], sys.argv[2], int(sys.argv[3])

with open(candidate_path, encoding='utf-8') as fh:
    candidate = json.load(fh)

# maker.sh uses tag as candidate metadata. It is not part of the outbound
# object schema in the generated fragment.
outbound = dict(candidate)
outbound_tag = str(outbound.pop('tag', 'singtest-out')) or 'singtest-out'

config = {
    'log': {
        'level': 'error'
    },
    'inbounds': [{
        'type': 'mixed',
        'tag': 'singtest-in',
        'listen': '127.0.0.1',
        'listen_port': port
    }],
    'outbounds': [
        dict(outbound, tag=outbound_tag),
        {
            'type': 'direct',
            'tag': 'direct'
        }
    ],
    'route': {
        'final': outbound_tag
    }
}

with open(config_path, 'w', encoding='utf-8') as fh:
    json.dump(config, fh, indent=2, ensure_ascii=False)
PY

###############################################################################
# Validate the temporary config first
###############################################################################
if ! "$SING_BOX" check -c "$CONFIG_FILE" >"$RUN_DIR/check.out" 2>&1; then
    printf 'status=INVALID_CONFIG\n' > "$RESULT_FILE"
    cat "$RUN_DIR/check.out" >&2
    rm -rf "$RUN_DIR"
    exit 1
fi

###############################################################################
# Check that the requested local SOCKS port is free
###############################################################################
if ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq '(^|:)127\.0\.0\.1:'"$PORT"'$|(^|:)0\.0\.0\.0:'"$PORT"'$|(^|:)\[::\]:'"$PORT"'$'; then
    fatal "Local test port $PORT is already in use. Use SINGTEST_PORT=<free-port>."
fi

###############################################################################
# Start temporary sing-box
###############################################################################
"$SING_BOX" run -c "$CONFIG_FILE" >"$PROBE_LOG" 2>"$PROBE_ERR" &
PID=$!

# Do not perform a raw TCP readiness probe here. The mixed inbound expects an
# actual protocol handshake. curl below is both the readiness test and the
# connectivity probe.

###############################################################################
# Real application-layer connectivity test
###############################################################################
info "Testing candidate..."
printf '  %-12s %s\n' 'Name' "$NAME"
printf '  %-12s %s\n' 'Protocol' "$PROTOCOL"
printf '  %-12s %s:%s\n' 'Endpoint' "$SERVER" "$SERVER_PORT"
printf '  %-12s %s/%s\n' 'Transport' "$TRANSPORT" "$SECURITY"
printf '  %-12s %s\n' 'Target' "$TARGET_URL"
printf '\n'

START_MS="$(date +%s%3N)"
set +e
timeout "$TIMEOUT" curl -fsS \
    --proxy "socks5h://127.0.0.1:$PORT" \
    --connect-timeout "$TIMEOUT" \
    --max-time "$TIMEOUT" \
    -o /dev/null \
    -w '%{http_code}\n' \
    "$TARGET_URL" >"$HTTP_CODE_FILE" 2>"$CURL_ERR"
CURL_RC=$?
set -e
END_MS="$(date +%s%3N)"
RESPONSE_MS=$((END_MS - START_MS))

HTTP_CODE="$(cat "$HTTP_CODE_FILE" 2>/dev/null || true)"

###############################################################################
# Result
###############################################################################
if (( CURL_RC == 0 )) && [[ "$HTTP_CODE" =~ ^[23][0-9][0-9]$ ]]; then
    printf 'status=PASS\n' > "$RESULT_FILE"
    printf 'response_ms=%s\n' "$RESPONSE_MS" >> "$RESULT_FILE"
    printf 'http_code=%s\n' "$HTTP_CODE" >> "$RESULT_FILE"
    printf 'curl_rc=%s\n' "$CURL_RC" >> "$RESULT_FILE"

    printf '\n'
    success "Connectivity PASS"
    printf '  Response : %sms\n' "$RESPONSE_MS"
    printf '  HTTP     : %s\n' "$HTTP_CODE"

    rm -rf "$RUN_DIR"
    exit 0
fi

printf 'status=FAIL\n' > "$RESULT_FILE"
printf 'response_ms=%s\n' "$RESPONSE_MS" >> "$RESULT_FILE"
printf 'http_code=%s\n' "$HTTP_CODE" >> "$RESULT_FILE"
printf 'curl_rc=%s\n' "$CURL_RC" >> "$RESULT_FILE"

printf '\n'
warning "Connectivity FAIL"
printf '  Response : %sms\n' "$RESPONSE_MS"
printf '  HTTP     : %s\n' "${HTTP_CODE:-000}"
printf '  Curl RC  : %s\n' "$CURL_RC"

if [[ -s "$CURL_ERR" ]]; then
    printf '\n--- curl error ---\n' >&2
    cat "$CURL_ERR" >&2
fi

if [[ -s "$PROBE_ERR" ]]; then
    printf '\n--- sing-box error ---\n' >&2
    cat "$PROBE_ERR" >&2
fi

printf '\nDiagnostics: %s\n' "$RUN_DIR" >&2

# Preserve diagnostics for a failed run; successful runs are cleaned up.
trap - EXIT INT TERM
cleanup
exit 1
