#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================================
# Smart Proxy Server - speedtest
#
# Measure download and upload throughput through ONE sing-box config.
#
# Usage:
#   bash speedtest.sh cache/validated/profile.json
#
# Optional environment variables:
#   SPEEDTEST_PORT=1235
#   SPEEDTEST_TIMEOUT=30
#   SPEEDTEST_DOWNLOAD_URL=https://speed.cloudflare.com/__down?bytes=10000000
#   SPEEDTEST_UPLOAD_URL=https://speed.cloudflare.com/__up
#   SPEEDTEST_DOWNLOAD_BYTES=10000000
#   SPEEDTEST_UPLOAD_BYTES=5000000
#
# The input may be either:
#   1) a complete sing-box configuration containing "outbounds"
#   2) a single outbound JSON fragment generated by maker.sh
#
# A temporary local SOCKS5 listener is created exactly like singtest.sh.
# ============================================================================

SING_BOX="${SING_BOX_BIN:-sing-box}"
PORT="${SPEEDTEST_PORT:-1235}"
TIMEOUT="${SPEEDTEST_TIMEOUT:-30}"
DOWNLOAD_URL="${SPEEDTEST_DOWNLOAD_URL:-https://speed.cloudflare.com/__down?bytes=${SPEEDTEST_DOWNLOAD_BYTES:-10000000}}"
UPLOAD_URL="${SPEEDTEST_UPLOAD_URL:-https://speed.cloudflare.com/__up}"
UPLOAD_BYTES="${SPEEDTEST_UPLOAD_BYTES:-5000000}"
WORK_ROOT="${SPEEDTEST_WORK_DIR:-/tmp/smartproxy-speedtest}"

fatal(){ printf '[✗] %s\n' "$*" >&2; exit 1; }
info(){ printf '[*] %s\n' "$*"; }
success(){ printf '[✓] %s\n' "$*"; }
warning(){ printf '[!] %s\n' "$*" >&2; }

usage(){
    printf 'Usage: %s <sing-box-config.json>\n' "$(basename "$0")" >&2
    exit 2
}

require_cmd(){
    command -v "$1" >/dev/null 2>&1 || fatal "Missing required command: $1"
}

[[ $# -eq 1 ]] || usage
INPUT="$1"
[[ -f "$INPUT" ]] || fatal "Config not found: $INPUT"

require_cmd "$SING_BOX"
require_cmd python3
require_cmd curl
require_cmd timeout
require_cmd ss

mkdir -p "$WORK_ROOT"
RUN_DIR="$WORK_ROOT/run-$$"
mkdir -p "$RUN_DIR"

CONFIG_FILE="$RUN_DIR/config.json"
ERR_FILE="$RUN_DIR/sing-box.err"
LOG_FILE="$RUN_DIR/sing-box.log"
META_FILE="$RUN_DIR/meta.txt"
PID=""

cleanup(){
    if [[ -n "${PID:-}" ]] && kill -0 "$PID" 2>/dev/null; then
        kill "$PID" 2>/dev/null || true
        wait "$PID" 2>/dev/null || true
    fi
    rm -rf "$RUN_DIR"
}
trap cleanup EXIT INT TERM

###############################################################################
# Build an isolated test config.
###############################################################################
python3 - "$INPUT" "$CONFIG_FILE" "$PORT" "$META_FILE" <<'PY'
import json
import os
import sys
from pathlib import Path

src = Path(sys.argv[1])
out = Path(sys.argv[2])
port = int(sys.argv[3])
meta = Path(sys.argv[4])

data = json.loads(src.read_text(encoding='utf-8'))
if not isinstance(data, dict):
    raise SystemExit('JSON root must be an object')

# Complete sing-box configuration.
if 'outbounds' in data:
    outbounds = data.get('outbounds') or []
    if not outbounds:
        raise SystemExit('full config contains no outbounds')

    wanted = os.environ.get('SPEEDTEST_OUTBOUND', '').strip()
    route = data.get('route') or {}
    if not wanted and isinstance(route, dict):
        final = route.get('final')
        if isinstance(final, str) and final:
            wanted = final

    if not wanted:
        for item in outbounds:
            if isinstance(item, dict) and item.get('tag'):
                wanted = str(item['tag'])
                break

    selected = next(
        (item for item in outbounds
         if isinstance(item, dict) and item.get('tag') == wanted),
        None,
    )
    if selected is None:
        raise SystemExit(f'outbound not found: {wanted}')

    cfg = dict(data)
    cfg['inbounds'] = [{
        'type': 'socks',
        'tag': 'speedtest-in',
        'listen': '127.0.0.1',
        'listen_port': port,
    }]
    cfg['route'] = dict(cfg.get('route') or {})
    cfg['route']['final'] = wanted
    cfg['route']['rules'] = []
    cfg.pop('experimental', None)
    out.write_text(json.dumps(cfg, indent=2, ensure_ascii=False), encoding='utf-8')

    transport = (selected.get('transport') or {}).get('type', 'tcp')
    tls = selected.get('tls') or {}
    security = 'tls' if tls.get('enabled') else 'none'
    with meta.open('w', encoding='utf-8') as f:
        print('mode=full', file=f)
        print(f'tag={wanted}', file=f)
        print(f"protocol={selected.get('type', 'unknown')}", file=f)
        print(f"server={selected.get('server', '-')}", file=f)
        print(f"port={selected.get('server_port', '-')}", file=f)
        print(f'transport={transport}', file=f)
        print(f'security={security}', file=f)
    raise SystemExit(0)

# Single outbound fragment.
outbound = dict(data)
tag = str(outbound.pop('tag', 'speedtest-out')) or 'speedtest-out'

cfg = {
    'log': {'level': 'error'},
    'inbounds': [{
        'type': 'socks',
        'tag': 'speedtest-in',
        'listen': '127.0.0.1',
        'listen_port': port,
    }],
    'outbounds': [
        dict(outbound, tag=tag),
        {'type': 'direct', 'tag': 'direct'},
        {'type': 'block', 'tag': 'block'},
    ],
    'route': {'final': tag, 'rules': []},
}
out.write_text(json.dumps(cfg, indent=2, ensure_ascii=False), encoding='utf-8')

transport = (outbound.get('transport') or {}).get('type', 'tcp')
tls = outbound.get('tls') or {}
security = 'tls' if tls.get('enabled') else 'none'
with meta.open('w', encoding='utf-8') as f:
    print('mode=fragment', file=f)
    print(f'tag={tag}', file=f)
    print(f"protocol={outbound.get('type', 'unknown')}", file=f)
    print(f"server={outbound.get('server', '-')}", file=f)
    print(f"port={outbound.get('server_port', '-')}", file=f)
    print(f'transport={transport}', file=f)
    print(f'security={security}', file=f)
PY

NAME="$(awk -F= '$1=="tag"{print $2}' "$META_FILE")"
PROTOCOL="$(awk -F= '$1=="protocol"{print $2}' "$META_FILE")"
SERVER="$(awk -F= '$1=="server"{print $2}' "$META_FILE")"
SERVER_PORT="$(awk -F= '$1=="port"{print $2}' "$META_FILE")"
TRANSPORT="$(awk -F= '$1=="transport"{print $2}' "$META_FILE")"
SECURITY="$(awk -F= '$1=="security"{print $2}' "$META_FILE")"

###############################################################################
# Validate configuration and local port.
###############################################################################
if ! "$SING_BOX" check -c "$CONFIG_FILE" >"$RUN_DIR/check.out" 2>&1; then
    printf '\n[!] Configuration check failed\n' >&2
    cat "$RUN_DIR/check.out" >&2
    exit 1
fi

if ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq '(^|:)127\.0\.0\.1:'"$PORT"'$|(^|:)0\.0\.0\.0:'"$PORT"'$|(^|:)\[::\]:'"$PORT"'$'; then
    fatal "Local test port $PORT is already in use. Use SPEEDTEST_PORT=<free-port>."
fi

###############################################################################
# Start sing-box.
###############################################################################
"$SING_BOX" run -c "$CONFIG_FILE" >"$LOG_FILE" 2>"$ERR_FILE" &
PID=$!

info "Starting speed test through sing-box..."
printf '  %-12s %s\n' 'Profile' "$NAME"
printf '  %-12s %s\n' 'Protocol' "$PROTOCOL"
printf '  %-12s %s:%s\n' 'Endpoint' "$SERVER" "$SERVER_PORT"
printf '  %-12s %s/%s\n' 'Transport' "$TRANSPORT" "$SECURITY"
printf '  %-12s %s\n' 'Download' "$DOWNLOAD_URL"
printf '  %-12s %s bytes\n' 'Upload' "$UPLOAD_BYTES"
printf '\n'

ready=0
for _ in {1..30}; do
    if ss -lnt 2>/dev/null | grep -Eq '[:.]'"$PORT"'[[:space:]]'; then
        ready=1
        break
    fi
    if ! kill -0 "$PID" 2>/dev/null; then
        break
    fi
    sleep 0.05
done

if (( ready == 0 )); then
    warning "sing-box test listener did not become ready"
    [[ -s "$ERR_FILE" ]] && cat "$ERR_FILE" >&2
    exit 1
fi

###############################################################################
# Download test.
# curl writes body to /dev/null and reports actual received bytes and time.
###############################################################################
set +e
DOWNLOAD_RESULT="$(curl -4 --http1.1 \
    --socks5-hostname "127.0.0.1:$PORT" \
    --connect-timeout 8 \
    --max-time "$TIMEOUT" \
    -sS -o /dev/null \
    -w '%{speed_download}|%{size_download}|%{time_total}|%{http_code}' \
    "$DOWNLOAD_URL" 2>"$RUN_DIR/download.err")"
DOWNLOAD_RC=$?

UPLOAD_RESULT="$(dd if=/dev/zero bs=1048576 count=$(( (UPLOAD_BYTES + 1048575) / 1048576 )) 2>/dev/null | head -c "$UPLOAD_BYTES" | \
    curl -4 --http1.1 \
    --socks5-hostname "127.0.0.1:$PORT" \
    --connect-timeout 8 \
    --max-time "$TIMEOUT" \
    -sS -o /dev/null \
    -X POST \
    -H 'Content-Type: application/octet-stream' \
    -w '%{speed_upload}|%{size_upload}|%{time_total}|%{http_code}' \
    --data-binary @- \
    "$UPLOAD_URL" 2>"$RUN_DIR/upload.err")"
UPLOAD_RC=$?
set -e

IFS='|' read -r DOWNLOAD_BPS DOWNLOAD_BYTES_DONE DOWNLOAD_TIME DOWNLOAD_HTTP <<< "$DOWNLOAD_RESULT"
IFS='|' read -r UPLOAD_BPS UPLOAD_BYTES_DONE UPLOAD_TIME UPLOAD_HTTP <<< "$UPLOAD_RESULT"

###############################################################################
# Format results.
###############################################################################
format_mbps(){
    awk -v bps="${1:-0}" 'BEGIN { if (bps+0 <= 0) printf "0.00"; else printf "%.2f", (bps*8)/1000000 }'
}

format_bytes(){
    awk -v n="${1:-0}" 'BEGIN {
        if (n < 1024) printf "%.0f B", n;
        else if (n < 1048576) printf "%.2f KiB", n/1024;
        else if (n < 1073741824) printf "%.2f MiB", n/1048576;
        else printf "%.2f GiB", n/1073741824;
    }'
}

DOWNLOAD_MBPS="$(format_mbps "$DOWNLOAD_BPS")"
UPLOAD_MBPS="$(format_mbps "$UPLOAD_BPS")"

printf '%s\n' '============================================================'
printf '%-18s %s\n' 'Download' "${DOWNLOAD_MBPS} Mbps"
printf '%-18s %s\n' 'Downloaded' "$(format_bytes "$DOWNLOAD_BYTES_DONE")"
printf '%-18s %ss\n' 'Download time' "${DOWNLOAD_TIME:-0}"
printf '%-18s %s\n' 'Download HTTP' "${DOWNLOAD_HTTP:-000}"
printf '%s\n' '------------------------------------------------------------'
printf '%-18s %s\n' 'Upload' "${UPLOAD_MBPS} Mbps"
printf '%-18s %s\n' 'Uploaded' "$(format_bytes "$UPLOAD_BYTES_DONE")"
printf '%-18s %ss\n' 'Upload time' "${UPLOAD_TIME:-0}"
printf '%-18s %s\n' 'Upload HTTP' "${UPLOAD_HTTP:-000}"
printf '%s\n' '============================================================'

if [[ "$DOWNLOAD_RC" -eq 0 && "$UPLOAD_RC" -eq 0 ]]; then
    success "Speed test completed"
    exit 0
fi

warning "Speed test completed with errors"
(( DOWNLOAD_RC != 0 )) && [[ -s "$RUN_DIR/download.err" ]] && cat "$RUN_DIR/download.err" >&2
(( UPLOAD_RC != 0 )) && [[ -s "$RUN_DIR/upload.err" ]] && cat "$RUN_DIR/upload.err" >&2
exit 1
