#!/usr/bin/env bash
set -Eeuo pipefail

# ============================================================================
# Smart Proxy Server
# Intelligence Proxy Engine
# Stage 3 : Validator
# ============================================================================
#
# Cheap application-layer validation for JSON candidates generated by maker.sh.
#
# Pipeline
#   maker.sh -> cache/generated/*.json -> validator.sh
#   Stage 1: one real proxy response test per candidate
#   Stage 2: three samples for the fastest candidates
#            -> median response time + jitter + stability
#   -> cache/validated/*.json -> score.sh
#
# No ICMP/ping is used here. Validation is performed through sing-box.
# Default concurrency is intentionally limited to 6 for small Orange Pi nodes.
# ============================================================================

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$BASE_DIR/config/defaults.conf"

GENERATED_DIR="${BASE_DIR}/cache/generated"
VALIDATED_DIR="${BASE_DIR}/cache/validated"
WORK_DIR="${BASE_DIR}/cache/validator"
RESULT_FILE="$WORK_DIR/results.tsv"
LOCK_FILE="/run/smartproxy-validator.lock"
LOCK_META="/run/smartproxy-validator.lock.info"

PARALLEL="${VALIDATOR_PARALLEL:-6}"
TOP_CANDIDATES="${VALIDATOR_TOP:-20}"
FINAL_TOP="${VALIDATOR_FINAL_TOP:-10}"
STAGE1_TIMEOUT="${VALIDATOR_STAGE1_TIMEOUT:-4}"
STAGE2_TIMEOUT="${VALIDATOR_STAGE2_TIMEOUT:-5}"
SING_BOX="${SING_BOX_BIN:-sing-box}"

fatal(){ printf '[✗] %s\n' "$*" >&2; exit 1; }
success(){ printf '[✓] %s\n' "$*"; }
warning(){ printf '[!] %s\n' "$*" >&2; }
info(){ printf '[*] %s\n' "$*"; }
require_cmd(){ command -v "$1" >/dev/null 2>&1 || fatal "Missing required command: $1"; }
is_number(){ [[ "${1:-}" =~ ^[0-9]+([.][0-9]+)?$ ]]; }

mkdir -p "$VALIDATED_DIR" "$WORK_DIR"
rm -f "$RESULT_FILE" "$VALIDATED_DIR"/*.json
: > "$RESULT_FILE"

# Prevent concurrent validator passes. The lock is held by FD 9 and therefore
# automatically released when this shell exits; the pathname itself is not a
# process lock and is never used as evidence of ownership.
exec 9>"$LOCK_FILE"
if ! flock -n 9; then
    lock_pid="$(cat "$LOCK_META" 2>/dev/null || true)"
    if [[ -n "$lock_pid" ]] && kill -0 "$lock_pid" 2>/dev/null; then
        warning "Another validator run is already active (PID $lock_pid)."
        exit 0
    fi
    warning "Validator lock is busy but owner metadata is stale; continuing."
fi
printf '%s\n' "$$" > "$LOCK_META"
trap 'rm -f "$LOCK_META"' EXIT

require_cmd "$SING_BOX"
require_cmd python3
require_cmd awk
require_cmd sort
require_cmd timeout
require_cmd curl
require_cmd flock

[[ -d "$GENERATED_DIR" ]] || fatal "Missing generated candidate directory: $GENERATED_DIR"

shopt -s nullglob
CANDIDATES=("$GENERATED_DIR"/*.json)
shopt -u nullglob
[[ ${#CANDIDATES[@]} -gt 0 ]] || fatal "No JSON candidates found in $GENERATED_DIR"

(( PARALLEL > 0 )) || fatal "VALIDATOR_PARALLEL must be > 0"
(( TOP_CANDIDATES > 0 )) || fatal "VALIDATOR_TOP must be > 0"
(( FINAL_TOP > 0 )) || fatal "VALIDATOR_FINAL_TOP must be > 0"

metadata(){
    python3 - "$1" <<'PY'
import json, sys
try:
    with open(sys.argv[1], encoding='utf-8') as fh:
        d=json.load(fh)
except Exception as exc:
    print(f"error={exc}")
    raise SystemExit(2)
transport=(d.get("transport") or {}).get("type", "tcp")
tls=(d.get("tls") or {})
print(f"name={d.get('tag','candidate')}")
print(f"server={d.get('server','')}")
print(f"port={d.get('server_port','')}")
print(f"transport={transport}")
print(f"security={'tls' if tls.get('enabled') else 'none'}")
PY
}

next_port(){ echo $((19080 + $1)); }

probe_once(){
    local candidate="$1" timeout_s="$2" run_dir="$3" socks_port="$4"
    local generated="$run_dir/config.json" pid="" start end elapsed curl_rc code

    python3 - "$candidate" "$generated" "$socks_port" <<'PY'
import json, sys
candidate_path, out_path, socks_port = sys.argv[1], sys.argv[2], int(sys.argv[3])
with open(candidate_path, encoding='utf-8') as fh:
    outbound=json.load(fh)
cfg={
  "log":{"level":"error"},
  "inbounds":[{"type":"mixed","tag":"validator-in","listen":"127.0.0.1","listen_port":socks_port}],
  "outbounds":[outbound,{"type":"direct","tag":"direct"}],
  "route":{"final":outbound.get("tag","")}
}
with open(out_path,'w',encoding='utf-8') as fh:
    json.dump(cfg,fh,ensure_ascii=False)
PY

    "$SING_BOX" check -c "$generated" >/dev/null 2>&1 || {
        printf 'status=invalid\nreason=sing-box-check\n' > "$run_dir/result"
        return 1
    }

    "$SING_BOX" run -c "$generated" >"$run_dir/probe.out" 2>"$run_dir/probe.err" &
    pid=$!

    local ready=0 i
    for i in {1..40}; do
        if (echo >/dev/tcp/127.0.0.1/"$socks_port") >/dev/null 2>&1; then
            ready=1
            break
        fi
        sleep 0.025
    done

    if (( ready != 1 )); then
        kill "$pid" 2>/dev/null || true
        wait "$pid" 2>/dev/null || true
        printf 'status=timeout\nreason=local-listener\n' > "$run_dir/result"
        return 1
    fi

    start="$(date +%s%3N)"
    set +e
    timeout "$timeout_s" curl -fsS \
        --proxy "socks5h://127.0.0.1:$socks_port" \
        --connect-timeout "$timeout_s" \
        --max-time "$timeout_s" \
        -o /dev/null \
        -w '%{http_code}\n' \
        'https://cp.cloudflare.com/generate_204' > "$run_dir/httpcode"
    curl_rc=$?
    set -e
    end="$(date +%s%3N)"
    elapsed=$(( end - start ))

    if (( curl_rc == 0 )); then
        code="$(cat "$run_dir/httpcode" 2>/dev/null || true)"
        case "$code" in
            2*|3*)
                printf 'status=ok\nrtt=%s\nhttp=%s\n' "$elapsed" "$code" > "$run_dir/result"
                kill "$pid" 2>/dev/null || true
                wait "$pid" 2>/dev/null || true
                return 0
                ;;
        esac
    fi

    printf 'status=failed\nrtt=%s\nhttp=%s\ncurl_rc=%s\n' \
        "$elapsed" "$(cat "$run_dir/httpcode" 2>/dev/null || true)" "$curl_rc" > "$run_dir/result"
    kill "$pid" 2>/dev/null || true
    wait "$pid" 2>/dev/null || true
    return 1
}

stage1_worker(){
    local candidate="$1" idx="$2"
    local meta name server port transport security run_dir result rtt status
    run_dir="$WORK_DIR/stage1_${idx}_$$"
    mkdir -p "$run_dir"

    meta="$(metadata "$candidate" 2>/dev/null || true)"
    if [[ "$meta" == error=* ]]; then
        rm -rf "$run_dir"
        return 0
    fi

    name="$(awk -F= '$1=="name"{print substr($0,index($0,"=")+1)}' <<< "$meta")"
    server="$(awk -F= '$1=="server"{print substr($0,index($0,"=")+1)}' <<< "$meta")"
    port="$(awk -F= '$1=="port"{print substr($0,index($0,"=")+1)}' <<< "$meta")"
    transport="$(awk -F= '$1=="transport"{print substr($0,index($0,"=")+1)}' <<< "$meta")"
    security="$(awk -F= '$1=="security"{print substr($0,index($0,"=")+1)}' <<< "$meta")"

    if probe_once "$candidate" "$STAGE1_TIMEOUT" "$run_dir" "$(next_port "$idx")" >/dev/null 2>&1; then
        result="$(cat "$run_dir/result" 2>/dev/null || true)"
        status="$(awk -F= '$1=="status"{print $2}' <<< "$result")"
        rtt="$(awk -F= '$1=="rtt"{print $2}' <<< "$result")"
        if [[ "$status" == ok ]] && is_number "$rtt"; then
            printf '%s\t%s\t%s\t%s\t%s\t%s\tstage1\n' \
                "$rtt" "$candidate" "$name" "$server" "$port" "$transport/$security" \
                >> "$RESULT_FILE"
        fi
    fi

    rm -rf "$run_dir"
}

info "Validating ${#CANDIDATES[@]} generated candidates..."
info "Stage 1: one real proxy response test per candidate (parallel=$PARALLEL)"

running=0
slot=0
pids=()
for candidate in "${CANDIDATES[@]}"; do
    ((slot+=1))
    stage1_worker "$candidate" "$(( (slot - 1) % PARALLEL ))" &
    pids+=("$!")
    ((running+=1))
    if (( running >= PARALLEL )); then
        wait "${pids[0]}" 2>/dev/null || true
        pids=("${pids[@]:1}")
        ((running-=1))
    fi
done
for pid in "${pids[@]}"; do
    wait "$pid" 2>/dev/null || true
done

STAGE1_COUNT="$(wc -l < "$RESULT_FILE" | tr -d ' ')"
info "Stage 1 valid: $STAGE1_COUNT / ${#CANDIDATES[@]}"
(( STAGE1_COUNT > 0 )) || fatal "No candidate passed Stage 1."

none_values="$(awk -F'\t' '$6 ~ /\/none$/ {print $1}' "$RESULT_FILE" | sort -n || true)"
tls_values="$(awk -F'\t' '$6 ~ /\/tls$/ {print $1}' "$RESULT_FILE" | sort -n || true)"
median_stream(){ awk '{a[NR]=$1} END {if(NR==0) exit 1; if(NR%2) print a[(NR+1)/2]; else print (a[NR/2]+a[NR/2+1])/2}' ; }
NONE_MEDIAN="$(printf '%s\n' "$none_values" | sed '/^$/d' | median_stream 2>/dev/null || true)"
TLS_MEDIAN="$(printf '%s\n' "$tls_values" | sed '/^$/d' | median_stream 2>/dev/null || true)"
NORMALIZE_OFFSET=0
if is_number "$NONE_MEDIAN" && is_number "$TLS_MEDIAN"; then
    NORMALIZE_OFFSET="$(awk -v n="$NONE_MEDIAN" -v t="$TLS_MEDIAN" 'BEGIN{d=t-n;if(d<0)d=-d;if(d>150)d=150;print d/2}')"
fi

STAGE2_LIST="$WORK_DIR/stage2.list"
awk -F'\t' -v off="$NORMALIZE_OFFSET" '
function adjusted(r, sec){if(sec ~ /\/none$/) return r+off; return r}
{print adjusted($1,$6) "\t" $0}
' "$RESULT_FILE" | sort -n -k1,1 | head -n "$TOP_CANDIDATES" | cut -f2- > "$STAGE2_LIST"

STAGE2_COUNT="$(wc -l < "$STAGE2_LIST" | tr -d ' ')"
info "Stage 2 candidates: $STAGE2_COUNT"
(( STAGE2_COUNT > 0 )) || fatal "No candidates selected for Stage 2."

STAGE2_RESULT="$WORK_DIR/stage2.tsv"
: > "$STAGE2_RESULT"

stage2_worker(){
    local row="$1" idx="$2"
    local rtt0 candidate name server port transport_security transport security
    IFS=$'\t' read -r rtt0 candidate name server port transport_security _ <<< "$row"
    transport="${transport_security%/*}"
    security="${transport_security##*/}"

    local run_dir="$WORK_DIR/stage2_${idx}_$$"
    mkdir -p "$run_dir"
    local values=() i result rtt
    for i in 1 2 3; do
        local probe_dir="$run_dir/test_$i"
        mkdir -p "$probe_dir"
        if probe_once "$candidate" "$STAGE2_TIMEOUT" "$probe_dir" "$(next_port "$((100 + idx * 3 + i))")" >/dev/null 2>&1; then
            result="$(cat "$probe_dir/result" 2>/dev/null || true)"
            rtt="$(awk -F= '$1=="rtt"{print $2}' <<< "$result")"
            is_number "$rtt" && values+=("$rtt")
        fi
    done

    if (( ${#values[@]} == 3 )); then
        IFS=$'\n' sorted=($(printf '%s\n' "${values[@]}" | sort -n))
        median="${sorted[1]}"
        min="${sorted[0]}"
        max="${sorted[2]}"
        jitter="$(awk -v a="$min" -v b="$max" 'BEGIN{print b-a}')"
        mean="$(awk -v a="${values[0]}" -v b="${values[1]}" -v c="${values[2]}" 'BEGIN{print (a+b+c)/3}')"
        stability="$(awk -v m="$mean" -v j="$jitter" 'BEGIN{if(m<=0){print 0}else{s=100-(j/m*100);if(s<0)s=0;if(s>100)s=100;printf "%.2f",s}}')"
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
            "$median" "$jitter" "$stability" "$candidate" "$name" "$transport" "$security" >> "$STAGE2_RESULT"
    fi

    rm -rf "$run_dir"
}

running=0
slot=0
pids=()
while IFS= read -r row; do
    ((slot+=1))
    stage2_worker "$row" "$slot" &
    pids+=("$!")
    ((running+=1))
    if (( running >= PARALLEL )); then
        wait "${pids[0]}" 2>/dev/null || true
        pids=("${pids[@]:1}")
        ((running-=1))
    fi
done < "$STAGE2_LIST"
for pid in "${pids[@]}"; do wait "$pid" 2>/dev/null || true; done

[[ -s "$STAGE2_RESULT" ]] || fatal "No candidate completed all three Stage 2 probes."

rm -f "$VALIDATED_DIR"/*.json
ranked="$WORK_DIR/ranked.tsv"
sort -t$'\t' -k3,3nr -k1,1n -k2,2n -k5,5 "$STAGE2_RESULT" > "$ranked"

index="$VALIDATED_DIR/index.tsv"
printf 'rank\tresponse_ms\tjitter_ms\tstability_pct\tcandidate\tname\ttransport\tsecurity\n' > "$index"
rank=0
while IFS=$'\t' read -r median jitter stability candidate name transport security; do
    ((rank+=1))
    printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
        "$rank" "$median" "$jitter" "$stability" "$candidate" "$name" "$transport" "$security" >> "$index"
    cp "$candidate" "$VALIDATED_DIR/$(printf '%02d' "$rank")_$(basename "$candidate")"
    (( rank >= FINAL_TOP )) && break
done < "$ranked"

FINAL_COUNT="$rank"
info "Stage 2 complete: $STAGE2_COUNT candidates tested x3"
success "Validator complete: $STAGE1_COUNT valid -> $STAGE2_COUNT retested -> $FINAL_COUNT selected"
printf 'Results: %s\n' "$index"
printf 'Normalization offset: %sms\n' "$NORMALIZE_OFFSET"
