OnUnitActiveSec=24h

LOG_DIR=/var/log/smartproxy
LOG_FILE=/var/log/smartproxy/proxy.log

SCANNER_PARALLEL=${SCANNER_PARALLEL:-8}
SCANNER_TOP=${SCANNER_TOP:-10}

VALIDATOR_PARALLEL=${VALIDATOR_PARALLEL:-4}
VALIDATOR_TOP=${VALIDATOR_TOP:-10}

SPEEDTESTER_PARALLEL=${SPEEDTESTER_PARALLEL:-2}
SPEEDTESTER_TOP=${SPEEDTESTER_TOP:-2}
