[worker]
Name=Nahan
Host=amir.irf.workers.dev
SNI=amir.irf.workers.dev
Ports=443,8443,80,8080

[vless]
UUID=2d556f14-54f5-a3ab-d6f5-943400000000
Transport=tcp,ws,grpc
Security=tls,none
Flow=
Fingerprint=chrome
AllowInsecure=false
ALPN=
WSPath=/sync
WSHost=
GRPCServiceName=
RealityPublicKey=
RealityShortID=
RealityServerName=

[trojan]
Password=
Transport=tcp,ws,grpc
Security=tls
Fingerprint=chrome
AllowInsecure=false
ALPN=
WSPath=/trojan
WSHost=
GRPCServiceName=
