[worker]
Name=Nahan
Host=amir.irf.workers.dev
SNI=amir.irf.workers.dev
Ports=443,8443,80,8080

[vless]
UUID=2d556f14-54f5-a3ab-d6f5-943400000000
Transport=tcp,ws
Security=tls,none
Flow=
Fingerprint=chrome
AllowInsecure=false
ALPN=
WSPath=/sync
WSHost=
GRPCServiceName=
RealityPublicKey=
RealityShortID=
RealityServerName=

[trojan]
Password=2d556f14-54f5-a3ab-d6f5-943402393af7
Transport=tcp,ws
Security=tls,none
Fingerprint=chrome
AllowInsecure=false
ALPN=
WSPath=/eyJqdW5rIjoiaUVMTUJkdFRIT2UiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W10sInJlbGF5SWR4IjowfQ==
WSHost=
GRPCServiceName=
